# Logging related
batch_logging_output_inc: 100

# GPU related
gpu_ids: [0, 1] # [-1] will set CPU for use
master_address: 'localhost'
master_port: '65531'

# Hyper parameters
epochs: 3
learning_rate: .00002

# Dataset & dataloader related
max_length: 512
batch_size: 16
num_labels: 2
num_workers: 4

