# Logging related
batch_logging_output_inc: 100

# GPU related
gpu_ids: [0] # [-1] will set CPU for use
master_address: 'localhost'
master_port: '65531'
use_mixed_precision: False

# Hyper parameters
epochs: 3
learning_rate: .001
input_size: 7
hidden_size: 50
output_size: 1
num_layers: 1
seq_length: 10

# Dataset & dataloader related
batch_size: 64
num_workers: 4
