# Logging related
batch_logging_output_inc: 100

# GPU related
gpu_ids: [0] # [-1] will set CPU for use
master_address: 'localhost'
master_port: '65531'
use_mixed_precision: False

# Hyper parameters
epochs: 3
learning_rate: 0.0001

# Dataset & dataloader related
num_workers: 4
batch_size: 64
num_classes: 10