# Logging related
batch_logging_output_inc: 100

# GPU related
gpu_ids: [4,5] # [-1] will set CPU for use
master_address: 'localhost'
master_port: '65531'
use_mixed_precision: True

# Hyper parameters
epochs: 3
learning_rate: .00002

# Dataset & dataloader related
max_length: 512
# batch_size: 16 # b1
batch_size: 16 # b2
num_labels: 2
num_workers: 4
